from piper import PiperVoice # needed for text to speech
import pygame # needed to play the wav files generated by piper
import wave # needed to read and write wav files

import sys # needed for printing errors to stderr
import time # needed for sleep

#tts_voice = PiperVoice.load("en_US-amy-medium.onnx") # load the piper voice for text to speech
#output_file = "output.wav" # the file where the generated speech will be saved

# initialize pygame mixer to play the generated wav file
pygame.mixer.init()

class Avatar_TTS:
    """
    Class that handles TTS calls for the avatar
    """

    def __init__(self, voice="en_US-amy-medium.onnx", output_file="output.wav"):
        """
        Initialize the Avatar_TTS instance.

        Args:
            voice (str): The voice model to use for text to speech.
            output_file (str): The file where the generated speech will be saved.
        """
        self.tts_voice = PiperVoice.load(voice)
        self.output_file = output_file
        pygame.mixer.init()

    def say(self, text):
        """
        sample method to turn text into speech

        Args:
            text (string): The text to be converted to speech
        """

        with wave.open(self.output_file, 'wb') as f:
            # set the parameters for the wav file

            # generate the speech and write it to the wav file
            self.tts_voice.synthesize_wav(text, f)

        # play the generated wav file
        pygame.mixer.Sound(self.output_file).play()

        while pygame.mixer.get_busy(): # wait for the audio to finish playing
            time.sleep(0.1)

if __name__ == "__main__":
    print("Text to Speech Test")

    while True:

        text = input("Enter text to convert to speech: ")
        if text.lower() == "exit":
            print("Exiting...")
            break
        
        avatar_tts = Avatar_TTS()
        avatar_tts.say(text)